### ISSUE TITLE
Question about code organization

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#10]
https://github.com/4ndyNMC/MetaU-Capstone/blob/9d4a4caa3c3e39d3bbb1a4b2d175e3e6e475db9b/app/src/main/java/com/example/metaucapstone/LoginActivity.java#L52

Consider doing some research into what the cleanest way to set onClick Listeners for Android is. I'm not sure, but I think if it were me I'd want to write up a separate function and just call that here with proper inputs if needed. I could be 10000% wrong here, but it would be dope to (as always, if there's enough time) try to show that you have the respect for your code to find the best/cleanest way to organize it :)

**Comment by 4ndyNMC** [comment]
Yeah, I'm not a fan of how clunky setting up each onClickListener is. I read [this article](https://medium.com/@CodyEngel/4-ways-to-implement-onclicklistener-on-android-9b956cbd2928) and I actually like "Option Two" a lot, which is where I store a View.OnClickListener in a field and do all of the work outside of the onCreate() method, and so it's pretty clean inside. I'm going to switch to using that, thanks!
