### ISSUE TITLE
Backlog TODO Comments

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#11]
https://github.com/4ndyNMC/MetaU-Capstone/blob/9d4a4caa3c3e39d3bbb1a4b2d175e3e6e475db9b/app/src/main/java/com/example/metaucapstone/LoginActivity.java#L94

It is good practice to leave a TODO comment here. @ Meta, we would also leave a task number (like we spoke about the other day) so that later we can go back and see that list of TODO tasks. If you're going to leave code like this that you probably want to go back and fix later, please check if there's a way you can reference a task or git issue or something here to remind yourself to back to it later. Maybe you could add a "backlog" section to your git plan. Just a thought.

**Comment by 4ndyNMC** [comment]
Oh snap you're right, I completely forgot about that method. The way to check is by making the request to sign up a user and check the error, which I do on line 112 so userExists() is just a throwaway method I forgot to get rid of.
But yes I'll make sure to more properly log something I need to do next time, thank you!
