### ISSUE TITLE
RE-Usable Code

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#12]
https://github.com/4ndyNMC/MetaU-Capstone/blob/9d4a4caa3c3e39d3bbb1a4b2d175e3e6e475db9b/app/src/main/java/com/example/metaucapstone/LoginActivity.java#L101

Would be super cool to see code that is 99% similar to other code in the app abstracted out into a re-usable function. For example, this and the login code are SUPER similar. You could just have like a bool input to switch the text or have the text input itself change. Maybe I'm missing something that would make it better for the code to be separate, but I think it would be cool to see this re-used.

**Comment by Bertogonz3000** [comment]
I do see there could be some difficulties here, but like there's potential to throw an error and deal with the error message in a generic way as well. Just worth a shot!

**Comment by 4ndyNMC** [comment]
Damn, thanks for making me go back to it lol. I remember looking at it and thinking it would be too annoying to abstract out the logic, but now knowing what I learned from condensing the OnClickListeners, I think I abstracted it really neatly and I'm kinda proud about doing it.

`    private OnCompleteListener authRequestComplete = new OnCompleteListener<AuthResult>() {
        @Override
        public void onComplete(@NonNull Task task) {
            if (task.isSuccessful()) {
                if (signingIn) {
                    User user = new User(auth.getCurrentUser().getEmail());
                    storeUser(user);
                }
                startActivity(new Intent(LoginActivity.this, MainActivity.class));
            } else if (task.getException().toString().contains("already in use")) {
                Snackbar.make(clLogin, "That email is already in use",
                        Snackbar.LENGTH_LONG).show();
            } else if (task.getException().toString().contains("password is invalid")) {
                Snackbar.make(clLogin, "Sorry, the password is incorrect",
                        Snackbar.LENGTH_LONG).show();
            } else {
                Snackbar.make(clLogin, "Sorry, there was an error",
                        Snackbar.LENGTH_LONG).show();
            }
        }
    };

    private void login(String username, String password) {
        signingIn = false;
        auth.signInWithEmailAndPassword(username, password).addOnCompleteListener(authRequestComplete);
    }

    private void signup(String username, String password) {
        signingIn = true;
        auth.createUserWithEmailAndPassword(username, password).addOnCompleteListener(authRequestComplete);
    }
`
