### ISSUE TITLE
Strings.xml

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#13]
https://github.com/4ndyNMC/MetaU-Capstone/blob/9d4a4caa3c3e39d3bbb1a4b2d175e3e6e475db9b/app/src/main/java/com/example/metaucapstone/LoginActivity.java#L143

Could be cool to learn how to use the strings.xml file. I could probably say something in your packet like "he went through the extra trouble of checking in all his strings so that this app could potentially be translated!

**Comment by 4ndyNMC** [comment]
Ah good point! I remember your feedback about that from a while ago which is why I have 14 strings stored in my `strings.xml` right now, but they're only for text views and stuff like that. I didn't think about using it for snackbar messages but that makes a lot of sense, thank you!
