### ISSUE TITLE
onCreate Cleanliness

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#14]
https://github.com/4ndyNMC/MetaU-Capstone/blob/main/app/src/main/java/com/example/metaucapstone/MainActivity.java#L48

Worth looking into the best way to structure an onCreate() method. I feel like in general I like seeing more modularization than you've had in yours. Like the bottom NAV logic could have it's own function called setupBottomNav() that you just call. You make a couple of different functions then it's super clear to any reader "oh hey he's setting up 4 or 5 different UI pieces here and if I want to know more about how he's doing it I can just find the corresponding function!"

**Comment by 4ndyNMC** [comment]
Yeah that's true; this specific instance looks much better now because, taking your advice from your [OnClickListener issue](https://github.com/4ndyNMC/MetaU-Capstone/issues/10), I moved the OnNavigationItemSelectedListener down below but I'll be sure to make my other onCreate methods cleaner.
