### ISSUE TITLE
semicolons?

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#15]
https://github.com/4ndyNMC/MetaU-Capstone/blob/main/app/src/main/java/com/example/metaucapstone/Recipe.java#L42

Whoa interesting that the formatter put 2 semicolons per line. Never seen that before!

**Comment by 4ndyNMC** [comment]
Oh, yeah I did that because I didn't want those data structure instantiations to be 80 lines long. Do you think I should change it to make it more linear?

**Comment by Bertogonz3000** [comment]
While it's legible this way it's fine and probably better form to make it more linear

**Comment by 4ndyNMC** [comment]
Fixed it!
