### ISSUE TITLE
TODO Comments

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#17]
https://github.com/4ndyNMC/MetaU-Capstone/blob/main/app/src/main/java/com/example/metaucapstone/RecipeAdapter.java#L67

Another good spot for those TODO comments I mentioned earlier.

I think this file in general could be a good spot for some of those TODO comments, since you'll likely come back and throw some more effort at the UI eventually.

**Comment by 4ndyNMC** [comment]
Yes! Definitely can and probably will put more TODOs here. I'm not sure why I left that comment there, though, since I send the recipe object to the recipe info page right above it; I guess I just forgot to remove it but I'll keep the feedback in mind.
