### ISSUE TITLE
Commented out code block.

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#19]
https://github.com/4ndyNMC/MetaU-Capstone/blob/main/app/src/main/java/com/example/metaucapstone/SearchResultFragment.java#L28

If you're going to leave big commented-out blocks like this, please leave a TODO comment reminding you to deal with it.

**Comment by 4ndyNMC** [comment]
Ok! Good feedback I'll do that in the future.
