### ISSUE TITLE
Static Variable initialization

### ISSUE THREAD

**Issue by Bertogonz3000** [4ndyNMC/MetaU-Capstone#20]
https://github.com/4ndyNMC/MetaU-Capstone/blob/main/app/src/main/java/com/example/metaucapstone/Spoonacular.java#L33

Feels a little odd to be setting/editing these static variables here. Would it be possible to do this when they are declared?

**Comment by 4ndyNMC** [comment]
Yeah.. I also thought it was annoying doing it that way, but the only problem is that I need a context object to access the API key via an xml file--or at least that's the easiest way. I agree that it's messy and unorthodox, but I feel that it's rather annoying to change right now so I might come back to it later unless you feel I should really put in the effort to change it.

**Comment by Bertogonz3000** [comment]
Oh I see cool no this works
